version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: infrastructure/web/Dockerfile
        ports:
            - "80:8000"
        volumes:
            - .:/app
            - laravel_storage:/app/storage
        environment:
            APP_NAME: PAS-Comunity
            APP_KEY: base64:swAdthTh8DOW4diF650kpz1bnZo+0sxImnvlCeR9KVE=
            APP_DEBUG: false
            APP_TIMEZONE: UTC
            APP_LOCALE: en
            APP_FALLBACK_LOCALE: en
            APP_ENV: production
            APP_URL: http://pas-comunity.test
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: db_PAS
            DB_USERNAME: root
            DB_PASSWORD: pascompass
            SESSION_DRIVER: database
            QUEUE_CONNECTION: database
            FILESYSTEM_DISK: local
            CACHE_STORE: database
        depends_on:
            - mysql
        networks:
            - app_network
        entrypoint: >
            sh -c "
            until nc -z mysql 3306; do
              echo 'Waiting for MySQL...';
              sleep 1;
            done;

            if [ ! -f /app/storage/migrations_done/migration.lock ]; then
              php artisan migrate --seed &&
              touch /app/storage/migrations_done/migration.lock;
            fi;

            php artisan octane:frankenphp
            "

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: db_PAS
            MYSQL_ROOT_PASSWORD: pascompass
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    laravel_storage:
    mysql_data:
