name: CI - CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: arjunamhv/pas-comunity:latest
  
  deploy:
    needs: build_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install ssh
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Execute SSH command
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no root@159.89.203.89 "cd pas-comunity/ && docker-compose down && docker system prune -af && docker compose build"
